### ISSUE TITLE
docs not available on hex

### ISSUE THREAD

**Issue by Strandinator** [gleam-community/codec#6]
I watched the Code BEAM Europe 2023 talk about end-to-end types and wanted to look through the hex docs for this package.

The other gleam-community packages seem to be available on hex, but not this one.
Is this code integrated in lustre and the codec package not needed anymore?

The link in the README points to this: https://hexdocs.pm/gleam_community_codec/

**Comment by jmrflora** [comment]
just came over to comment the same thing.

**Comment by kuechlerm** [comment]
The link to https://hex.pm/packages/gleam_community_codec is also broken.
Is this package dead?

**Comment by hayleigh-dot-dev** [comment]
This package has not yet been published! The standard library is about to break decoders in favour of a different approach so we'll be waiting until that releases before we revisit this and solve some rough spots in the API I couldn't figure out the first time round.
